name: segment_anything
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - loguru=0.5.3
  - uvicorn=0.20.0
  - fastapi=0.95.1
  - python-multipart=0.0.6
  - janus=1.0.0
  - numpy=1.23.5
  - pandas=2.1.4
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - mkl=2021.4.0
  - torchvision=0.15.0
  - onnx=1.13.0
  - onnxruntime=1.12.1
  - matplotlib=3.7.1
  - pip=23.0.1
  - pip:
      - mpmath==1.2.1
      - opencv-python==4.7.0.72
      - pyqt5-sip==12.11.0
      - segment-anything==1.0
