name: sam_service
services:
    nginx:
        image: nginx
        container_name: sam_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/sam.conf
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
    sam:
        image: ghcr.io/janeliascicomp/sam_service:sessions
        depends_on:
            - nginx
        restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
